---
version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - PORT=80
